# Generated by Django 3.0.4 on 2020-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=9)),
                ('employee_iex_id', models.CharField(max_length=7)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_wave', models.CharField(max_length=8)),
                ('employee_team_leader', models.CharField(max_length=255)),
                ('employee_manager', models.CharField(max_length=255)),
                ('employee_hire_date', models.DateField()),
            ],
        ),
    ]
