# Generated by Django 3.0.4 on 2020-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='employee_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
